---
name: 💥 Bug/Crash report
description: File a bug/issue
title: "[BUG] <title>"
labels: [Bug, Needs Triage]
body:
- type: checkboxes
  attributes:
    label: General Info
    description: You may select more than one.
    options:
    - label: I did not add any mods.
    - label: I can reproduce this issue consistently in single-player
    - label: I can reproduce this issue consistently in multi-player
    - label: I am crashing and can provide my crash report(s)
      required: true
- type: textarea
  attributes:
    label: Your launcher version
    description: for example curseforge.
  validations:
    required: false
- type: textarea
  attributes:
    label: Modpack version
    description: for example 1.0 or .05
  validations:
    required: false
- type: textarea
  attributes:
    label: Descripbe your issue
    description: A clear and concise description of what the bug is.
  validations:
    required: false
- type: textarea
  attributes:
    label: reproducue steps
    description: 1. go for a walk 2. jump 3. run
  validations:
    required: false
- type: textarea
  attributes:
    label: Additionly info
    description: | plese post a crash report if your game has crashed( located in crash folder or latest.log) or use paste bin
      

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false

---


